### ISSUE TITLE
Add Aurora interior to logic

### ISSUE THREAD

**Issue by tinyhoot** [tinyhoot/SubnauticaRandomiser#12]
Scout out the Aurora and note what can be obtained with which tools. Obviously, there's a lot of loot boxes, but this mostly ties into **fragments**.

Without sequence breaking, the Aurora is only available once it has exploded, so a radiation suit is always required. Once inside, there are four tools necessary:
- Fire extinguisher. There's enough of these lying around that the crafting recipe could be considered optional. Even if you run out, you can run through the flames.
- Propulsion gun. Or repulsion, either one works. Several entryways are blocked by debris, most notably the lower main entrance leading to the labs below the prawn bay. The large corridor in the upper main entrance is also blocked, but skippable with some well-timed jumps.
- Repair tool. Repairing the reactor is little more than QoL, but a few doors have broken access panels.
- Laser cutter. I'm not actually too sure, but I _think_ the labs below the prawn bay have a door or two requiring it.

Properly mapping out the Aurora then allows for randomising the fragments within, as well as the blueprint you get from the labs, and maybe also the Seamoth Depth Module and Cyclops Energy Efficiency Module lying around. These last two should never be required to progress though (except in hard mode maybe?), keep them as fun little bonuses.

**Comment by InfernalUnderling** [comment]
Is there any specific data you need about what's in the rooms (e.g. coords, some kind of object ID, etc)?

I'm planning on replaying the game in the near future, so if you let me know what info you need, I can take notes on what's where as I'm going through the ship.
