### ISSUE TITLE
Impossible Seed

### ISSUE THREAD

**Issue by jet082** [tinyhoot/SubnauticaRandomiser#35]
The seed requires the compass for the alien habitat. However, the compass is hidden in two locations - each behind laser-cutter requirements. The laser cutter, however, requires a Stalker.

Following the logic of the seed, it seems like it is 'possible' to beat the seed, but that it is probably impossible to build a base - since each power supply options requires the alien habitat, which is impossible to build (you almost can power a base without it - but apparently unidentified eggs do not count for recipes).

Maybe this is not an issue, but I think for most players being unable to power a base would make something functionally impossible.

Spoiler log, DataFiles, and config.json attached.

[spoilerlog.zip](https://github.com/tinyhoot/SubnauticaRandomiser/files/9375637/spoilerlog.zip)

**Comment by jet082** [comment]
I'm also not sure the seaglide fragments ever got formed... I could not seem to find any in the provided locations. Moreover, the spoiler log seems to think that I should be able to build the rebreather, but that requires an Ampeel, which is impossible to get due to the compass requirement.

**Comment by tinyhoot** [comment]
I can confirm that this seed is beatable, at least as long as you are able to reach the compass blueprint. The one in wreck1 is reachable without a laser cutter by squirming through the hole in the hull right next to it. However, I just learned today that this specific databox actually becomes inaccessible from the outside after the aurora explodes! Overall a simple fix and everything else seems to work as intended. If anything, perhaps guarantee an early power option without complex requirements like seeds/eggs.

**Comment by tinyhoot** [comment]
> I'm also not sure the seaglide fragments ever got formed... I could not seem to find any in the provided locations.

That's the part that really breaks this seed's neck though. Instead of being distributed properly, both the seaglide and the seamoth had their fragments all lumped in at Degasi base 2, which seems related to #34 and #36. Will fix!
