### ISSUE TITLE
Max ingredients per recipe set to 1 doesn't work

### ISSUE THREAD

**Issue by sophice** [tinyhoot/SubnauticaRandomiser#43]
Hello! Love this mod, really revitalizes the game!

I wanted to try an easy mode attempt before bumping up the difficulty and I set "Max number of a single ingredient" to 1, and "Max ingredients per recipe" to 1, expecting single-ingredient recipes. It seems that everything still requires two separate ingredients (but only 1 of each), so the "Max ingredients per recipe" setting of 1 seemingly isn't working.

Am I misunderstanding it, or is that a limit of the game, or is it a fixable scenario with that particular setting? If it's a limitation of the game, maybe that option slider should just stop at 2 and not allow an input of 1, to make it clearer?

Thanks!

**Comment by tinyhoot** [comment]
Hey, sorry for the late reply.

I've been able to identify and fix the issue. It will be rolled out with the next release. Thanks so much for reporting.
