### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by Evistos** [tinyhoot/SubnauticaRandomiser#46]
Hi everyone,

I can't make this mod work. I believe I installed it correctly though.
There is my installation folder and the error.

![Folders](https://user-images.githubusercontent.com/117576973/200171309-07bee27b-4319-41ab-ae55-30f21d6799bd.PNG)
![Inside folder](https://user-images.githubusercontent.com/117576973/200171314-3c79cbce-f767-4369-a2e6-ffd985a9613f.PNG)
![Error](https://user-images.githubusercontent.com/117576973/200171315-f4f84fd4-82bb-4109-b7ba-4815c97a639c.PNG)

All mods are up to date. I already have verify the game files and did a clean install.

Inside my config.json:

{
    "iSeed": 0,
    "iRandomiserMode": 0,
    "sSpawnPoint": "Vanilla",
    "bUseFish": true,
    "bUseEggs": false,
    "bUseSeeds": true,
    "bRandomiseDataboxes": true,
    "bRandomiseFragments": true,
    "bRandomiseNumFragments": true,
    "bRandomiseDuplicateScans": true,
    "bRandomiseRecipes": true,
    "bVanillaUpgradeChains": false,
    "bDoBaseTheming": false,
    "iEquipmentAsIngredients": 0,
    "iToolsAsIngredients": 0,
    "iUpgradesAsIngredients": 1,
    "iMaxAmountPerIngredient": 5,
    "iMaxIngredientsPerRecipe": 7,
    "iMaxBiomesPerFragment": 5,
    "iMaxFragmentsToUnlock": 5,
    "ADVANCED_SETTINGS_BELOW_THIS_POINT": "ADVANCED_SETTINGS_BELOW_THIS_POINT",
    "iDepthSearchTime": 15,
    "iMaxBasicOutpostSize": 24,
    "iMaxDepthWithoutVehicle": 200,
    "iMaxDuplicateScanYield": 2,
    "iMaxEggsAsSingleIngredient": 1,
    "iMaxFragmentsPerBiome": 4,
    "iMaxInventorySizePerRecipe": 24,
    "iMinFragmentsToUnlock": 2,
    "dPrimaryIngredientValue": "0.45",
    "dRecipeValueVariance": "0.2",
    "fFragmentSpawnChanceMin": "0.3",
    "fFragmentSpawnChanceMax": "0.6",
    "sBase64Seed": "",
    "iSaveVersion": 4
}

Thanks a lot for your time!

**Comment by tinyhoot** [comment]
That's really odd. Everything looks installed correctly. I figured maybe it's related to the QModManager update last week but that works just fine on my machine as well.

Does it happen multiple times, i.e. every time you start up the game? If yes, try changing the "iSeed" value in the config to 880378095 and see if it works. Might be getting unlucky with an unsolvable seed.

**Comment by Evistos** [comment]
Yes it happens every time. I just tried with 880378095 instead of 0 for "iSeed", without success

**Comment by tinyhoot** [comment]
Alright. I'll need some more detailed logs for this. In the main menu, please go to Options -> Mods -> QModManager and tick "Enable debug logs". Then, restart the game. This will generate a qmodmanager_log-Subnautica.txt file in your Subnautica folder. Please post this file here.

**Comment by Evistos** [comment]
Oh you're right, I saw this earlier but completly forgot about it!

[qmodmanager_log-Subnautica.txt](https://github.com/tinyhoot/SubnauticaRandomiser/files/9946423/qmodmanager_log-Subnautica.txt)

It was generated without any action from me, so just in case I generated another with your instructions 

[qmodmanager_log-Subnautica.txt](https://github.com/tinyhoot/SubnauticaRandomiser/files/9946426/qmodmanager_log-Subnautica.txt)

**Comment by tinyhoot** [comment]
I think I might have found the issue. Try replacing your SubnauticaRandomiser.dll with this one I cooked up in testing.
[SubnauticaRandomiser_CultureTesting.zip](https://github.com/tinyhoot/SubnauticaRandomiser/files/9946756/SubnauticaRandomiser.dll.zip)

**Comment by Evistos** [comment]
It works! Thanks a lot! What was the issue?

**Comment by tinyhoot** [comment]
I'm releasing a proper version of this as a minor version update.
