### ISSUE TITLE
Randomise fragments and their required number

### ISSUE THREAD

**Issue by tinyhoot** [tinyhoot/SubnauticaRandomiser#5]
Fragments are already partially in logic, ensuring that no item can be required before it has been possible to unlock its blueprint. Expanding on this logic with extended information about wrecks could improve on the randomiser in three ways:

- Knowing which wrecks require e.g. a laser cutter to access the databoxes within could fix potential softlocks.
- By having more information about the wrecks, it becomes possible to track every single fragment of a blueprint, opening the doors to dynamically requiring more or fewer of them each run while still knowing exactly at what depth the item remains accessible.
- If we know where each fragment is, perhaps it is possible to swap them around and randomise their locations?

**Comment by Raqzas** [comment]
Complication: Subnautica does not do static fragments. They change with every time the save game is loaded, even if you save right on top of them. While changing the number of required fragments (within reason, say, up to 5-6?) is a relatively simple thing to do, changing their spawns appears a lot more complicated than at first thought.
