### ISSUE TITLE
Scanned & Collected blueprints & fragments are not saving

### ISSUE THREAD

**Issue by aazza94** [tinyhoot/SubnauticaRandomiser#52]
I have the randomiser set up (2.0 new version) and it seemed to be working perfectly to begin with.

However, I noticed when collecting databox blueprints & scanning various things (in this case, it was the observatory, multipurpose room and various planters etc.) when the game is saved & restarted, you lose them.

Even the databox resets itself which is the oddest thing. It makes the mod unusable to me, because I dont see a point in having to rescan everything every time I turn it on 

I am guessing this was not intentional, I just wanted to bring it to your attention because I LOVE this mod. I just cannot use it with the above current issue :( also, it was my only mod. so definitely no clashing going on.

**Comment by tinyhoot** [comment]
Sorry to hear. Lucky for you, this is a known issue in SMLHelper and already fixed. Make sure you're on the latest version of SMLHelper (2.15.0.**1**).
