### ISSUE TITLE
Impossible To Research Seaglide

### ISSUE THREAD

**Issue by jet082** [tinyhoot/SubnauticaRandomiser#54]
I believe that this seaglide is impossible to research. Spent 4 or 5 hours trying to find it to no avail.

Looking at the spoiler log, it seems there are only 3 fragments that got generated, but 5 are required to build it. 3 is all I found in-game.

[spoilerlog.txt](https://github.com/tinyhoot/SubnauticaRandomiser/files/10326937/spoilerlog.txt)
[alternateStarts.csv](https://github.com/tinyhoot/SubnauticaRandomiser/files/10326942/alternateStarts.csv)
[biomeSlots.csv](https://github.com/tinyhoot/SubnauticaRandomiser/files/10326943/biomeSlots.csv)
[recipeInformation.csv](https://github.com/tinyhoot/SubnauticaRandomiser/files/10326944/recipeInformation.csv)
[wreckInformation.csv](https://github.com/tinyhoot/SubnauticaRandomiser/files/10326945/wreckInformation.csv)

**Comment by tinyhoot** [comment]
The spoiler log shows you that the fragment gets generated in three different biomes. How many fragments actually spawn is up to the game. I'm getting the same issue as you though, so I'm increasing spawn rates for all three of those biomes.

**Comment by jet082** [comment]
I did end up finding the remaining parts - I found six in total (of the five needed). For some reason they were incredibly slanted towards the area around the aurora.
