### ISSUE TITLE
Dynamically adjust duplicate scan rewards

### ISSUE THREAD

**Issue by tinyhoot** [tinyhoot/SubnauticaRandomiser#62]
Adjust the resources returned from scanning fragments you've already unlocked dynamically. For example, based on the current maximum depth, or the recipe of whatever was scanned.

**Comment by RayRobertson72** [comment]
> Adjust the resources returned from scanning fragments you've already unlocked dynamically. For example, based on the current maximum depth, or the recipe of whatever was scanned.

Ah, from the recipe sounds cool too. Would you be able to receive fish, seeds and eggs too?

**Comment by tinyhoot** [comment]
I've done more researching and talking and I think resources from recipes is better handled by Parts From Scanning. It already does a great job and there's no point in reinventing the wheel. Making the generic rewards more dynamic should still be a goal though.

**Comment by RayRobertson72** [comment]
> I've done more researching and talking and I think resources from recipes is better handled by Parts From Scanning. It already does a great job and there's no point in reinventing the wheel. Making the generic rewards more dynamic should still be a goal though.

Of course. Would they have applied weights to plant seeds, fish and eggs?

**Comment by tinyhoot** [comment]
I don't know. I'll have to look into how exactly things are implemented, but modded resources are also supposed to work, which is already a good sign.

**Comment by tinyhoot** [comment]
#65 touches on this a bit. While it doesn't introduce full dynamic rewards, it does add a proper loot table with some more interesting rare rewards. I'm tempted to leave it at that and let Parts From Scanning handle any more complex scenarios.
