### ISSUE TITLE
Start with all eggs identified

### ISSUE THREAD

**Issue by tinyhoot** [tinyhoot/SubnauticaRandomiser#64]
Patch things so that all eggs start as their identified versions, skipping the need for an ACU.

Although now fixed, this also counteracts the underlying issue in #42

**Comment by RayRobertson72** [comment]
> Patch things so that all eggs start as their identified versions, skipping the need for an ACU.
> 
> Although now fixed, this also counteracts the underlying issue in #42

I don’t wish to give you extra work, but in case this change makes that the Unknown Name mod doesn’t make them unidentified, could it be made optional?

**Comment by tinyhoot** [comment]
This has always been intended as an option, I just did not word it clearly.

**Comment by RayRobertson72** [comment]
> This has always been intended as an option, I just did not word it clearly.
> 
> The patch for this is extremely simple, it just adds all eggs to KnownTech on starting a new game. I'm not sure how Unknown Name works or how it interacts with this.

Okay, cool cool.
