### ISSUE TITLE
Wrong blueprints are being checked when spawning data boxes

### ISSUE THREAD

**Issue by ItsTheKais** [tinyhoot/SubnauticaRandomiser#75]
I found that the Water Filtration Suit and Cyclops Docking Bay Repair Upgrade were AWOL in my save, even after triple-checking every wreck, lifepod, and Degasi habitat. I opened the spoiler log and found data box coordinates for both, but using the warp command teleported me to five spots that very definitely lacked data boxes.

A vanilla Subnautica mechanic is that data boxes will not spawn if, upon loading the area for the first time, the player already has the blueprint it contains. So I did some testing. One of the coordinates given for the Docking Bay Repair Upgrade was [-1206, -225, 4], which is inside one of the Dunes wrecks. The data box at those coordinates normally contains the Reinforced Dive Suit blueprint.

- I started a new game and immediately used the warp command to go to those coordinates. A data box spawned there, containing the Repair Upgrade.
- I started a new game again, used the unlock command to unlock the Repair Upgrade, then used the warp command again. A data box spawned, containing the Repair Upgrade, even though I already had that blueprint.
- I started a new game again, used the unlock command to unlock the Reinforced Dive Suit, then used the warp command again. No data box spawned!

The game appears to still be checking for a data box's vanilla blueprint, instead of the randomized blueprint, when deciding whether to spawn that data box. As I experienced in my save, this can cause perfectly-obtainable blueprints to become unobtainable mid-run through pure bad luck.

**Comment by tinyhoot** [comment]
Thanks for the detailed report. That's a regression, probably stemming from the new patch method for databoxes. I'm a bit confused on why it's occurring though, since the patch should happen before the duplicate check.
